
    Template.compile(["<h3 class='RegisterHeader'>Almost Done!</h3>\n\n<p>You're now <b>ready</b> to use ProcrasDonate to make pledges!  \n\n<p><i>Deposit</i> to your <a href=\"http://tipjoy.com\">TipJoy</a> account to <b>turn your pledges into donations</b>.\n<br>You can use the same Twitter username and password for <a href=\"http://tipjoy.com\">Tipjoy</a>.</p>\n\n<p>Your current <i>balance</i> is......... <b>$</b><span id='balance_here'>(retrieving from TipJoy...)</span>.</p>\n"], "balance_middle");
    
    Template.compile(["<h3 class='RegisterHeader'>Donation and Goal options (can be changed later.)</h3>\n\t\n<form name='account_form' onSubmit='return false'>\n\t<p>How many <b>pennies/hour</b> will you donate when <i>ProcrasDonating</i>?</p>\n\t<table>\n\t\t<tbody>\n\t\t\t\t<td><input class='form-right form-value' type='text' size='4' name='cents_per_hr' value='", ["var", ["cents_per_hr"], []], "'></td>\n\t\t\t\t<td><div class='help form-left form-label'>&cent; per hour</div></td>\n\t\t\t</tr>\n\t\t</tbody>\n\t</table>\n\t<p>What is your <b>goal</b>? How much procrasdonaton are you <i>striving</i> for?</p>\n\t<table>\n\t\t<tbody>\t\t\t\t\n\t\t\t<tr>\n\t\t\t\t<td><input class='form-right form-value' id='hr_per_week_goal' type='text' size='4' name='hr_per_week_goal' value='", ["var", ["hr_per_week_goal"], []], "'></td>\n\t\t\t\t<td>\n\t\t\t\t\t<div class='help form-left form-label'>hours per week</div>\n\t\t\t\t\t<span id='cents_per_week_goal'></span>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t</tbody>\n\t</table>\t\t\t\n\t<p>What is your <b>limit</b>? No pledges will be made <i>past</i> your weekly limit.</p>\n\t<table>\n\t\t<tbody>\n\t\t\t<tr>\n\t\t\t\t<td><input class='press_enter_for_next form-right form-value' id='hr_per_week_max' type='text' size='4' name='hr_per_week_max' value='", ["var", ["hr_per_week_max"], []], "'></td>\n\t\t\t\t<td><div class='help form-left form-label'>hours per week</div></td>\n\t\t\t</tr>\n\t\t</tbody>\n\t</table>\n</form>\n"], "donation_amounts_middle");
    
    Template.compile(["<div id='ranks'>\n\t<h2>", ["var", ["context", "title"], []], "</h2>\n\t", ["var", ["context", "test"], []], ["var", ["context", "test", "0"], []], "\n\t", ["for", ["x"], ["var", ["context", "test"], []], false, ["\n\t\tx=", ["var", ["x"], []], "\n\t"]], "\n\t", ["for", ["submenus"], ["var", ["context", "submenus"], []], false, ["\n\t\ts:", ["var", ["submenus"], []], "\n\t\t<div class=\"submenu_column\">\n\t\t\t<ul>\n\t\t\t\t", ["for", ["item"], ["var", ["submenus"], []], false, ["\n\t\t\t\t\t<li class=\"link ", ["if", [[false, ["var", ["item", "selected"], []]]], 1, ["selected"], []], "\">\n\t\t\t\t\t\t", ["var", ["item", "name"], []], "\n\t\t\t\t\t\t", ["if", [[false, ["var", ["item", "coming"], []]]], 1, ["<small>(coming soon)</small>"], []], "\n\t\t\t\t\t</li>\n\t\t\t\t"]], "\n\t\t\t</ul>\n\t\t</div>\n\t"]], "\n\t\n\t<div class='rank_legend'>\n\t\t<h3>Legend</h3>\n\t\t", ["for", ["class_name"], ["var", ["context", "class_names"], []], false, ["\n\t\t\t<label>", ["var", ["class_name"], []], "</label>\n\t\t\t<div class=\"bar ", ["var", ["class_name"], []], "\"></div>\n\t\t"]], "\n\t</div>\n\t\n\t<h3>", ["var", ["context", "sub_title"], []], "</h3>\n\t<table>\n\t\t<tbody>\n\t\t\t", ["for", ["row"], ["var", ["context", "data"], []], false, ["\n\t\t\t<tr class=\"rank\">\n\t\t\t\t<td class=\"name\">", ["var", ["row", "name"], []], "</td>\n\t\t\t\t<td class=\"rank\">\n\t\t\t\t\t<div class=\"bar ", ["var", ["row", "class_name"], []], "\" style=\"width: ", ["var", ["row", "pct"], []], "%\">\n\t\t\t\t\t\t<div class=\"rank_text\">", ["var", ["row", "total"], []], "</div>\n\t\t\t\t\t</div>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t"]], "\n\t\t</tbody>\n\t</table>\n\n</div>"], "impact_middle");
    
    Template.compile(["<div id='ranks'>\n\t<h3>Most Supported Recipient</h3>\n</div>\n<table>\n\t<tbody>\n\t\t", ["for", ["row"], ["var", ["data"], []], false, ["\n\t\t<tr class=\"rank\">\n\t\t\t<td class=\"name\">", ["var", ["row", "recipient_name"], []], "</td>\n\t\t\t<td class=\"rank\">\n\t\t\t\t<div class=\"bar\" style=\"width: ", ["var", ["row", "amount_pct"], []], "%\">\n\t\t\t\t\t<div class=\"rank_text\">$", ["var", ["row", "total_amount"], []], "</div>\n\t\t\t\t</div>\n\t\t\t</td>\n\t\t</tr>\n\t\t"]], "\n\t</tbody>\n</table>\n<hr>\n<table>\n\t<tbody>\n\t\t", ["for", ["row"], ["var", ["data"], []], false, ["\n\t\t<tr class=\"rank\">\n\t\t\t<td class=\"name\">", ["var", ["row", "recipient_name"], []], "</td>\n\t\t\t<td class=\"rank\">\n\t\t\t\t<div class=\"bar\" style=\"width: ", ["var", ["row", "time_pct"], []], "%\">\n\t\t\t\t\t<div class=\"rank_text\">", ["var", ["row", "total_time"], []], "</div>\n\t\t\t\t</div>\n\t\t\t</td>\n\t\t</tr>\n\t\t"]], "\n\t</tbody>\n</table>"], "impact_recipients_middle");
    
    Template.compile(["<div id='ranks'>\n\t<!--<fieldset class='rank_legend' style='-moz-border-radius:1em;'>-->\n\t<div class='rank_legend'>\n\t\t<h3>Site Classification Legend</h3>\n\t\t<!--<legend>Legend</legend>-->\n\t\t<label>ProcrasDonate:</label><div class='bar procrasdonate'></div>\n\t\t<label>TimeWellSpent:</label><div class='bar timewellspent'></div>\n\t\t<label>Other:</label><div class='bar other'></div>\n\t</div>\n\t<!--</fieldset>-->\n\t<h3>Most Visited Sites</h3>\n</div>\n<table>\n\t<tbody>\n\t\t", ["for", ["row"], ["var", ["data"], []], false, ["\n\t\t<tr class=\"rank\">\n\t\t\t<td class=\"name\">", ["var", ["row", "sitegroup_name"], []], "</td>\n\t\t\t<td class=\"rank\">\n\t\t\t\t<div class=\"bar ", ["var", ["row", "tag"], []], "\" style=\"width: ", ["var", ["row", "amount_pct"], []], "%\">\n\t\t\t\t\t<div class=\"rank_text\">$", ["var", ["row", "total_amount"], []], "</div>\n\t\t\t\t</div>\n\t\t\t</td>\n\t\t</tr>\n\t\t"]], "\n\t</tbody>\n</table>\n<hr>\n<table>\n\t<tbody>\n\t\t", ["for", ["row"], ["var", ["data"], []], false, ["\n\t\t<tr class=\"rank\">\n\t\t\t<td class=\"name\">", ["var", ["row", "sitegroup_name"], []], "</td>\n\t\t\t<td class=\"rank\">\n\t\t\t\t<div class=\"bar ", ["var", ["row", "tag"], []], "\" style=\"width: ", ["var", ["row", "time_pct"], []], "%\">\n\t\t\t\t\t<div class=\"rank_text\">", ["var", ["row", "total_time"], []], "</div>\n\t\t\t\t</div>\n\t\t\t</td>\n\t\t</tr>\n\t\t"]], "\n\t</tbody>\n</table>"], "impact_sites_middle");
    
    Template.compile(["<div id='thin_column'>\n\t", ["var", ["tab_snippet"], []], "\n\t<div id='messages'></div>\n\t<div id='errors'></div>\n\t<div id='success'></div>\n\t", ["var", ["middle"], []], "\n</div>\n\n"], "impact_wrapper_snippet");
    
    Template.compile(["<div class=\"site\">\n\t", ["var", ["inner"], []], "\n</div>\n\n"], "make_site_box");
    
    Template.compile([["var", ["inner"], []], "\n<span class='img_link move_to_unsorted'>\n\t<img class='Move_Site_Arrow' src='", ["var", ["constants", "MEDIA_URL"], []], "img/RightArrow.png'>\n</span>\n"], "procrasdonate_wrap");
    
    Template.compile(["<div class='recipient'>\n\t<!-- id class needed for js -->\n\t<div class=\"recipient_id\">", ["var", ["id"], []], "</div>\n\t<div class='add_recipient' title=\"Add recipient to list\"> \n\t\t<img src=\"", ["var", ["MEDIA_URL"], []], "img/AddRecipient.png\">\t\t\n\t </div>\n\t<div class='name'><a href='", ["var", ["url"], []], "'>", ["var", ["name"], []], "</a></div>\n\t<div class='mission'>", ["var", ["mission"], []], "</div>\n\t<div class='link description_toggle'>(less)</div>\n\t<div class='description'>", ["var", ["description"], []], "</div>\n</div>\n"], "recipient_snippet");
    
    Template.compile(["<div class='recipient'>\n\t<!-- id class needed for js -->\n\t<div class=\"recipient_id\">", ["var", ["id"], []], "</div>\n\t<div class='remove_recipient' title=\"Remove recipient from list\">\n\t\t<img src=\"", ["var", ["MEDIA_URL"], []], "img/Remove.png\" class=\"small-image\">\t\t\n\t</div>\n\t<div class='recipient_percent'>\n\t\t<input type=\"text\" name=\"percent\" id=\"recipient_", ["var", ["id"], []], "\" size='2' value=\"", ["var", ["percent"], []], "\" />\n\t\t<div class='percent_symbol'>%</div>\n\t</div>\n\t<div class='name'><a href='", ["var", ["url"], []], "'>", ["var", ["name"], []], "</a></div>\n\t<div class='mission'>", ["var", ["mission"], []], "</div>\n\t<div class='link description_toggle'>(less)</div>\n\t<div class='description'>", ["var", ["description"], []], "</div>\n</div>\n"], "recipient_with_percent_snippet");
    
    Template.compile(["<h3 class='RegisterHeader'>Your charitable recipients.</h3>\n<p><ul>\n\t<li>Add non-profits from the list at the bottom.</li>\n\t<li>Then assign a percentage of your pledges to each of your selections.</li>\n</ul></p>\n<div id='user_recipients'>\n\t", ["var", ["user_recipients"], []], "\n</div>\n<div id='potential_recipients'>\n\t", ["var", ["potential_recipients"], []], "\n</div>\n\n"], "recipients_middle");
    
    Template.compile(["<h3 class='RegisterHeader'>Begin categorizing websites.</h3>  \n\t<p>\n\t\tClick on the green arrows to move websites to the appropriate column.  \n\t</p><p>\n\t\tYou can also classify these and other sites using the icons that will appear on your firefox browser.\n\t</p>\n\t\n<div id='site_classifications'>\n\t<div id='procrasdonate_col' class='column'>\n\t\t<div class='title'>\n\t\t\t<img src=\"", ["var", ["MEDIA_URL"], []], "img/ProcrasDonateLogoNoText.png\" class=\"small-image\">\t\t\n\t\t\tProcrasDonate\n\t\t</div>\n\t\t", ["var", ["procrasdonate_text"], []], "\n\t</div>\n\t<div id='unsorted_col' class='column'>\n\t\t<div class='title'>\n\t\t\t<img src=\"", ["var", ["MEDIA_URL"], []], "img/ToolbarImages/UnsortedIcon.png\" class=\"small-image\">\t\t\n\t\t\tUnsorted\n\t\t</div>\n\t\t", ["var", ["unsorted_text"], []], "\n\t</div>\n\t<div id='timewellspent_col' class='column'>\n\t\t<div class='title'>\n\t\t\t<img src=\"", ["var", ["MEDIA_URL"], []], "img/ThumbsUp.png\" class=\"small-image\">\t\t\n\t\t\tTime Well Spent\n\t\t</div>\n\t\t", ["var", ["timewellspent_text"], []], "\n\t</div>\n</div>\n"], "site_classifications_middle");
    
    Template.compile(["<h3 class='RegisterHeader'>What is ProcrasDonate worth to you?</h3>\n\n<p>What <b>percentage</b> of <i>your</i> donations should we use to run/improve our service?</p>\n\t\n<form name='account_form' onSubmit='return false'>\n\t<table>\n\t\t<tbody>\n\t\t\t<tr>\n\t\t\t\t<td><label class='form-right form-label'>Support ProcrasDonate: </label></td>\n\t\t\t\t<!-- <td><div id='support_slider' class='slider' alt='", ["var", ["pct"], []], "'></div></td>-->\n\t\t\t\t<td><input id='support_input' class='press_enter_for_next input form-value form-right' alt='", ["var", ["pct"], []], "' value='", ["var", ["pct"], []], "' size='2'/></td>\n\t\t\t\t<td><span class='help form-label form-right'>% of total donation</span></td>\n\t\t\t</tr>\n\t\t</tbody>\n\t</table>\n</form>\n"], "support_middle");
    
    Template.compile(["<span class='img_link move_to_unsorted'>\n\t<img class='Move_Site_Arrow' src='", ["var", ["constants", "MEDIA_URL"], []], "img/LeftArrow.png'>\n</span>\n", ["var", ["inner"], []], "\n"], "timewellspent_wrap");
    
    Template.compile(["<form name='account_form' onSubmit='return false'>\n\t\n\t<h3>Please sign in using your Twitter account:</h3>\n\t\n\t<table>\n\t\t<tbody>\n\t\t\t<tr>\n\t\t\t\t<td><label class='form-right'>Twitter username </label></td>\n\t\t\t\t<td><input class='form-left' type='text' name='twitter_username' value='", ["var", ["twitter_username"], []], "'></td>\n\t\t\t\t<td class='form-left'>\n\t\t\t\t\t\tClick <a href='https://twitter.com/signup'>HERE</a> if you're not on twitter yet.\n\t\t\t\t\t\t<a id='what_is_twitter' class='link'>What is Twitter?</a>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t\n\t\t\t<tr>\n\t\t\t\t<td><label class='form-right'>Twitter password</label></td>\n\t\t\t\t<td><input class='press_enter_for_next form-left' type='password' name='twitter_password' value='", ["var", ["twitter_password"], []], "'></td>\n\t\t\t\t<td class='help form-left'>\n\t\t\t\t\t\tYour Twitter password is only revealed to \n\t\t\t\t\t\t<a href=\"http://TipJoy.com\">TipJoy</a> for handling micro-payments:\n\t\t\t\t\t\t<a href='", ["var", ["constants", "PRIVACY_URL"], []], "'>Privacy Guarantee</a>\n\t\t\t\t\t</td>\n\t\t\t</tr>\n\t\t</tbody>\n\t</table>\n\t<table>\n\t\t<tbody>\n\t\t\t<tr>\n\t\t\t\t<td><input class='right' type='checkbox' name='tos' value='agree' /></td>\n\t\t\t\t<td><label class='left'>I agree to the Terms of Use</label></td>\n\t\t\t</tr>\t\t\n\t\t</tbody>\n\t</table>\n\t\n\t<h2><a name='tos'></a>Terms of Use</h2>\n\t<img src='", ["var", ["constants", "MEDIA_URL"], []], "img/TermsOfUse.png' class='small-image'>\n\t<p>By using our service you agree to the following:\n\t\t<ul class='paragraph_list'>\n\t\t\t<li>ProcrasDonate may update these terms of service without warning or notification.\n\t\t\t<li>You understand how our service works and are willingly participating.\n\t\t\t<li>You agree to pay all pledges made on your behalf in full.\n\t\t\t<li>A percentage that you determine of your donations is donated to our service.\n\t\t\t<li>You are responsible for any content you add to this site.\n\t\t\t<li>Illegal, unfriendly, or otherwise problematic content will be removed.\n\t\t\t<li>Your individual records and settings are private and not accessible by our company.\n\t\t\t<li>Your summary records are used for community statistics and other as yet undetermined uses (hopefully that will support the service financially).\n\t\t\t<li>All rights are reserved including ProcrasDonate intellectual property of software and our business model.\n\t\t\t</li><li><b>Thanks for ProcrasDonating!</b>\n\t\t</ul>\n\t</p>\n\t\n</form>\n"], "twitter_account_middle");
    
    Template.compile(["<span class='img_link move_to_procrasdonate'>\n\t<img class='Move_Site_Arrow' src='", ["var", ["constants", "MEDIA_URL"], []], "img/LeftArrow.png'>\n</span>\n", ["var", ["inner"], []], "\n<span class='img_link move_to_timewellspent'>\n\t<img class='Move_Site_Arrow' src='", ["var", ["constants", "MEDIA_URL"], []], "img/RightArrow.png'>\n</span>\n"], "unsorted_wrap");
    
    Template.compile(["<div id='thin_column'>\n\t", ["var", ["tab_snippet"], []], "\n\t<div id='messages'></div>\n\t<div id='errors'></div>\n\t<div id='success'></div>\n\t", ["var", ["middle"], []], "\n</div>\n\n"], "wrapper_snippet");
    