
/**
 * Generated by xpi builder on the fly when user downloads extension.
 */
function generated_input() {
    return [{"private_key": "qP8iwSHDIH1GkCWgNnVlKk", "preselected_charities": [{"percent": 0.0, "recipient_slug": "BILUMI"}]}]
}
