
/**
 * Generated by xpi builder on the fly when user downloads extension.
 */
function generated_input() {
    return [{"constants_PD_URL": "https://ProcrasDonate.com", "constants_PD_API_URL": "https://ProcrasDonate.com", "private_key": "oCREtlFOB0W1W0wtFi5G9A", "preselected_charities": [{"percent": 0.0, "recipient_slug": "bilumi"}]}]
}
